// components/Tablature/index.tsx
import { useEffect, useState } from "react"
import { getScaleAfterKeyConvert, scalePushMapping, scalePullMapping, scalePushList, scalePullList } from "./setting"


function Tablature(props:{ input: {
    def: string,
    scales?: Array<string>,
    tabs?: Array<string>,

}, style?: any }) {
    var size = "25px"
    var width = "300px"
    var border = "0px"
    if(props.style){
        if(props.style.size){
            size = props.style.size
        }
        if(props.style.width){
            width = props.style.width
        }
        if(props.style.border){
            border = props.style.border
        }
    }
    const leftFirstStyle = {
        marginLeft: "15px",
    }
    const leftSecStyle = {
        marginLeft: "10px",
    }
    const leftThirStyle = {
    }
    const rightFirstStyle = {
    }
    const rightSecStyle = {
        marginLeft: "10px",
    }
    const rightThirStyle = {
        marginLeft: "20px",
    }
    const tablatureConcertina = {
        margin: "5px",
        display: "flex",
        FlexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: width,
        border:border
    }
    const [tab, setTab] = useState({
        l1a: "#aaa",
        l2a: "#aaa",
        l3a: "#aaa",
        l4a: "#aaa",
        l5a: "#aaa",
        l1: "#aaa",
        l2: "#aaa",
        l3: "#aaa",
        l4: "#aaa",
        l5: "#aaa",
        l6: "#aaa",
        l7: "#aaa",
        l8: "#aaa",
        l9: "#aaa",
        l10: "#aaa",
        r1a: "#aaa",
        r2a: "#aaa",
        r3a: "#aaa",
        r4a: "#aaa",
        r5a: "#aaa",
        r1: "#aaa",
        r2: "#aaa",
        r3: "#aaa",
        r4: "#aaa",
        r5: "#aaa",
        r6: "#aaa",
        r7: "#aaa",
        r8: "#aaa",
        r9: "#aaa",
        r10: "#aaa",
    })
    useEffect(()=>{
        var temp:any = {
            l1a: "#aaa",
            l2a: "#aaa",
            l3a: "#aaa",
            l4a: "#aaa",
            l5a: "#aaa",
            l1: "#aaa",
            l2: "#aaa",
            l3: "#aaa",
            l4: "#aaa",
            l5: "#aaa",
            l6: "#aaa",
            l7: "#aaa",
            l8: "#aaa",
            l9: "#aaa",
            l10: "#aaa",
            r1a: "#aaa",
            r2a: "#aaa",
            r3a: "#aaa",
            r4a: "#aaa",
            r5a: "#aaa",
            r1: "#aaa",
            r2: "#aaa",
            r3: "#aaa",
            r4: "#aaa",
            r5: "#aaa",
            r6: "#aaa",
            r7: "#aaa",
            r8: "#aaa",
            r9: "#aaa",
            r10: "#aaa",
        }
        if(props.input.scales){
            for(var i = 0; i < props.input.scales.length; i++){
                var scale:string = props.input.scales[i]
                if(props.input.def == "push"){
                    var k:string = scalePushMapping[scale]
                    temp[k] = "red"
                }else{
                    const k = scalePullMapping[scale]
                    temp[k] = "blue"
                }
            } 
        }
        if(props.input.tabs){
            for(var i = 0; i < props.input.tabs.length; i++){
                var k:string = props.input.tabs[i]
                if(props.input.def == "push"){
                    temp[k] = "red"
                }else{
                    temp[k] = "blue"
                }
            } 
        }
        if(!props.input.tabs && !props.input.scales){
            temp = {
                l1a: "#aaa",
                l2a: "#aaa",
                l3a: "#aaa",
                l4a: "#aaa",
                l5a: "#aaa",
                l1: "#aaa",
                l2: "#aaa",
                l3: "#aaa",
                l4: "#aaa",
                l5: "#aaa",
                l6: "#aaa",
                l7: "#aaa",
                l8: "#aaa",
                l9: "#aaa",
                l10: "#aaa",
                r1a: "#aaa",
                r2a: "#aaa",
                r3a: "#aaa",
                r4a: "#aaa",
                r5a: "#aaa",
                r1: "#aaa",
                r2: "#aaa",
                r3: "#aaa",
                r4: "#aaa",
                r5: "#aaa",
                r6: "#aaa",
                r7: "#aaa",
                r8: "#aaa",
                r9: "#aaa",
                r10: "#aaa",
            }
        }
        setTab(temp)
    },[props])
    
    

    return (
        <div style={mainTablature}>
            <div style={tablatureConcertina}>
                <div id="left">
                    <div style={leftFirstStyle}>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l1a}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l2a}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l3a}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l4a}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l5a}}/>
                    </div>
                    <div style={leftSecStyle}>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l1}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l2}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l3}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l4}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l5}}/>
                    </div>
                    <div style={leftThirStyle}>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l6}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l7}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l8}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l9}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.l10}}/>
                    </div>
                </div>
                <div id="right">
                    <div style={rightFirstStyle}>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r1a}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r2a}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r3a}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r4a}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r5a}}/>
                    </div>
                    <div style={rightSecStyle}>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r1}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r2}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r3}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r4}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r5}}/>
                    </div>
                    <div style={rightThirStyle}>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r6}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r7}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r8}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r9}}/>
                        <span className="dot" style={{height:size,width:size,backgroundColor: tab.r10}}/>
                    </div>
                </div>
            </div>
        </div>
    )
}

export {Tablature, getScaleAfterKeyConvert, scalePushMapping, scalePullMapping, scalePushList, scalePullList}

const defaultStyle = {
    tablatureConcertina : {
        margin: "5px",
        display: "flex",
        FlexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "300px",
    },
    rowHight: "28px",
    padding: "5px"

}

 
const mainTablature = {
    display: "flex",
    FlexDirection: "row",
    alignItems: "center",
    justifyContent: "center"
}



//   #tablature-concertina #left #first {
//     margin-left:10px;
//   }
//   #tablature-concertina #left #second {
//     margin-left:5px;
//   }
//   #tablature-concertina #right #third {
//     margin-left:10px;
//   }
//   #tablature-concertina #right #second {
//     margin-left:5px;
//   }
//   #tablature-concertina .dot {
//     height: 15px;
//     width: 15px;
//     /* background-color: #bbb; */
//     border-radius: 50%;
//     display: inline-block;
//   }

// src/components/Tablature.vue
<script setup>
</script>

<template>
  <transition name="modal" @after-leave="afterLeave">
    <div id="nav-tablature">
      <div id="tablature-concertina">
        <div id="left">
          <div id="first">
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l1a }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l2a }"></span>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l3a }"></span>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l4a }"></span>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l5a }"/>
          </div>
          <div id="second">
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l1 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l2 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l3 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l4 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l5 }"/>
          </div>
          <div id="third">
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l6 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l7 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l8 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l9 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.l10 }"/>
          </div>
        </div>
        <div id="right">
          <div id="first">
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r1a }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r2a }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r3a }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r4a }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r5a }"/>
          </div>
          <div id="second">
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r1 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r2 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r3 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r4 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r5 }"/>
          </div>
          <div id="third">
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r6 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r7 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r8 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r9 }"/>
            <span class="dot" v-bind:style="{ backgroundColor: concertina.r10 }"/>
          </div>
        </div>
      </div>
    </div>
  </transition>
</template>

<script>
import {scalePushMapping, scalePullMapping} from './Settings.vue'

export default {
    props: ['scales', 'def'],
    setup(props){
    },
    data() {
      return {
        concertina: {
          l1a: "#bbb",
          l2a: "#bbb",
          l3a: "#bbb",
          l4a: "#bbb",
          l5a: "#bbb",
          l1: "#bbb",
          l2: "#bbb",
          l3: "#bbb",
          l4: "#bbb",
          l5: "#bbb",
          l6: "#bbb",
          l7: "#bbb",
          l8: "#bbb",
          l9: "#bbb",
          l10: "#bbb",
          r1a: "#bbb",
          r2a: "#bbb",
          r3a: "#bbb",
          r4a: "#bbb",
          r5a: "#bbb",
          r1: "#bbb",
          r2: "#bbb",
          r3: "#bbb",
          r4: "#bbb",
          r5: "#bbb",
          r6: "#bbb",
          r7: "#bbb",
          r8: "#bbb",
          r9: "#bbb",
          r10: "#bbb",
        }
      }
    },
    mounted: function () {

    },
    watch: {},
    methods: {
    },
    created() {
      console.log(this.scales)
      this.scales.forEach((scale)=>{
        if(this.def == "push"){
          const k = scalePushMapping[scale]
          this.concertina[k] = "red"
        }else{
          const k = scalePullMapping[scale]
          this.concertina[k] = "blue"
        }
      })
    }
  }
</script>


<style lang="scss">
@forward 'vuetify/settings' with (
  $slider-vertical-min-height: 100px,
);
.color {
	stroke: #ddd !important;
	fill: red !important;
  color: red !important;
}


#nav-tablature{
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
}
#tablature-concertina{
  margin: 5px;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  width: 180px;
  border: 1px solid black;
}
#tablature-concertina #first {
  height: 18px;
}
#tablature-concertina #second {
  height: 18px;
}
#tablature-concertina #third {
  height: 18px;
}
#tablature-concertina #left #first {
  margin-left:10px;
}
#tablature-concertina #left #second {
  margin-left:5px;
}
#tablature-concertina #right #third {
  margin-left:10px;
}
#tablature-concertina #right #second {
  margin-left:5px;
}
#tablature-concertina .dot {
  height: 15px;
  width: 15px;
  /* background-color: #bbb; */
  border-radius: 50%;
  display: inline-block;
}

</style>
